/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "../../packages/flash-calendar/src/components",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-ignore
    req: require.context(
      '../../../packages/flash-calendar/src/components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  },
  {
    titlePrefix: "",
    directory: "./src/components",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-ignore
    req: require.context(
      '../src/components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var STORYBOOK_WEBSOCKET: { host: string; port: number } | undefined;
}


const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview")
];

globalThis.STORIES = normalizedStories;


// @ts-ignore
module?.hot?.accept?.();



if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,

  });
} else {
  updateView(globalThis.view, annotations, normalizedStories);
}

export const view: View = globalThis.view;
